syncbook final version

diff --git a/syncbook b/syncbook
--- a/syncbook
+++ b/syncbook
@@ -1,16 +1,34 @@
 #!/bin/bash
 
-# 定义本地备份目录和远程目标目录
+# Function to get SSH parameters from .ssh/config
+get_ssh_param() {
+    local alias="$1"
+    local param="$2"
+    local value=$(awk -v alias="$alias" -v param="$param" 'BEGIN{IGNORECASE=1} /^Host\s/ && $2 == alias {found=1} found && $1 == param {sub(/^\s*/, "", $2); print $2; exit} END {if (!found) exit 1}' ~/.ssh/config)
+    echo "$value"
+}
+
+# Check if a parameter is provided
+if [ -z "$1" ]; then
+    echo "Usage: $0 <hostname>"
+    exit 1
+fi
+
+# Get SSH parameters
+remote_host_alias="$1"
+remote_host=$(get_ssh_param "$remote_host_alias" "HostName")
+[ -z "$remote_host" ] && echo "Host $remote_host_alias not found in ~/.ssh/config" && exit 1
+remote_user=$(get_ssh_param "$remote_host_alias" "User")
+[ -z "$remote_user" ] && echo "user is not defined in host: $remote_host_alias " && exit 1
+remote_port=$(get_ssh_param "$remote_host_alias" "Port" || echo "22") # Default port 22 if not found
+
+# Define local and remote directories
 local_dir="/backup/ebook"
-remote_user="user"
-remote_host="192.168.168.125"
-remote_port="2222"
 remote_dir="/sdcard"
 remote_screenshots_dir="/sdcard/koreader/screenshots"
 local_screenshots_dir="/backup/koreader"
 
-# 使用rsync进行增量同步
-rsync -avz --inplace --no-perms --progress -e "ssh -p $remote_port -o StrictHostKeyChecking=no" --exclude '.DS_Store' --exclude '.git' --exclude '.svn' $local_dir $remote_user@$remote_host:$remote_dir
-
-rsync -avz --inplace --progress -e "ssh -p $remote_port -o StrictHostKeyChecking=no" --exclude '.DS_Store' --exclude '.git' --exclude '.svn' $remote_user@$remote_host:$remote_screenshots_dir $local_screenshots_dir
+# Use rsync for incremental synchronization
+rsync -avz --inplace --no-perms --progress -e "ssh -p $remote_port -o StrictHostKeyChecking=no" --exclude '.DS_Store' --exclude '.git' --exclude '.svn' "$local_dir" "$remote_user@$remote_host:$remote_dir"
+rsync -avz --inplace --progress -e "ssh -p $remote_port -o StrictHostKeyChecking=no" --exclude '.DS_Store' --exclude '.git' --exclude '.svn' "$remote_user@$remote_host:$remote_screenshots_dir" "$local_screenshots_dir"
 
